### PR TITLE
Add variables for build tools versions

### PR DESCRIPTION
**Pull request by yongce**

### CODE REVIEW

**Comment by yongce** [comment]
done

**Comment by slinzner** [comment]
Happy to take this CL in, but we just did a new push. Can you pls rebase and update this CL. While we're add it can you add more variables for supportLibVersion, runnerVersion, rulesVersion, espressoVersion and uiautomatorVersion.

Ty

**Comment by yongce** [comment]
done

**Comment by slinzner** [comment]
Thanks, LGTM. Can you please sign the Google CLA, i suppose you signed the Android one. I cannot merge this CL unless you sign this.

**Comment by yongce** [comment]
It's done to sign the Google CLA.

**Comment by slinzner** [comment]
Thanks yongce!

**Pull request merged**
